/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vigilant.octo.winner;

// EJERCICIO: Ingresar a la pagina https://gorest.co.in/
// Consumir el API: https://gorest.co.in/public/v2/users
// La encontrará en la seccion de RESOURCES
// El ejercicio consiste en consumir esa API y mostrar los valores: id, name, email, gender y estatus.

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
